//
// Developed by:  Mario Emmenlauer (mario@emmenlauer.de)
//                Balanstrasse 43, 81669 Munich
//                http://www.biodataanalysis.de/
//
// With contributions by:
//
//
// Copyright (c) 2014-2018, BioDataAnalysis GmbH
// All Rights Reserved.
//
// Redistribution and use in source and binary forms, with or without
// modification, are not permitted. All information contained herein
// is, and remains the property of BioDataAnalysis GmbH.
// Dissemination of this information or reproduction of this material
// is strictly forbidden unless prior written permission is obtained
// from BioDataAnalysis GmbH.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
//

#ifndef APIACCESSCLONEFACTORY_HH
#define APIACCESSCLONEFACTORY_HH

#include <TestThriftAPIHandler.hh>

#include <thrift/transport/TServerSocket.h>
#include <thrift/transport/TSocket.h>

#include <iostream>

/**
 * @brief TestThriftAPICloneFactory inherits from TestThriftAPI::TestThriftAPIIfFactory
 * to provide access to the server side of the transport. It is also useful for
 * making per-connection state. Without this CloneFactory, all connections
 * will end up sharing the same handler instance.
 * @note TestThriftAPIIfFactory is automatically generated by thrift.
 */
class TestThriftAPICloneFactory : virtual public TestThriftAPI::TestThriftAPIIfFactory {
public:
    TestThriftAPICloneFactory() = default;
    virtual ~TestThriftAPICloneFactory() = default;

    virtual TestThriftAPI::TestThriftAPIIf* getHandler(const apache::thrift::TConnectionInfo& connInfo);

    virtual void releaseHandler(TestThriftAPI::TestThriftAPIIf* handler);
};

#endif
